# Generated by Django 4.2.5 on 2023-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitecrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
